In [1]:
import pandas as pd
import numpy as np
import scipy
import sklearn
import nltk
import pickle
from tensorflow import keras
import tensorflow as tf
from sklearn.preprocessing import OneHotEncoder

C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\framework\dtypes.py:516: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\framework\dtypes.py:517: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\framework\dtypes.py:518: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\framework\dtypes.py:519: FutureWarning: Passi

In [2]:

data = pd.read_csv(('twitter_dataset.csv'),encoding = "ISO-8859-1")
print(data.shape)
data.head()
print(data['sentiment'].unique())

(40000, 2)
['fun' 'worry' 'neutral' 'surprise' 'happiness' 'sadness' 'relief' 'love'
 'boredom' 'hate' 'enthusiasm' 'anger' 'empty']


In [3]:
from sklearn.model_selection import train_test_split
data = data.fillna(' ')
train_data , test_data = train_test_split(data,test_size=0.20)
print(train_data.shape)
print(train_data.head())

(32000, 2)
                                                 content   sentiment
29658  " complete black books " arrived . looking for...     neutral
36382                                        oh hangover     neutral
27039                              cheers defo give call     neutral
39705                                       oh ok thanks  enthusiasm
4520                happy star wars day =d hbd uncle lee   happiness


In [4]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(token_pattern = r"(?u)\b\w+\b")

X_train = cv.fit_transform(data["content"])
encoded = cv.vocabulary_

In [5]:
data1 = data.copy()
new_datacon=[]
for i in data1['content']:
  k=[]
  for j in i:
    try :
      k.append(encoded[j])
    except:
      continue
  new_datacon.append(k)
data1['content']= new_datacon
print(data1.head())
print(len(data1['sentiment']))

                                             content  sentiment
0  [28825, 1631, 26121, 5165, 12325, 19612, 18971...        fun
1  [13501, 16486, 22961, 15401, 9103, 9103, 19612...      worry
2  [30054, 27939, 19612, 26121, 12325, 9103, 3005...    neutral
3  [21579, 9103, 1631, 15401, 15401, 30054, 5165,...   surprise
4  [12325, 26121, 26121, 19612, 26121, 28825, 135...  happiness
40000


In [6]:
import numpy as np
from keras.utils import to_categorical
cats = data1['sentiment']
### Universal list of colors
total_cats = data['sentiment'].unique()

print(total_cats)

### map each color to an integer
mapping = {}
for x in range(len(total_cats)):
  mapping[total_cats[x]] = x

# integer representation
for x in range(len(cats)):
  cats[x] = mapping[cats[x]]

onehotencoded = to_categorical(cats)
print(onehotencoded)
data1['sentiment'] = onehotencoded
print(data1['sentiment'])

['fun' 'worry' 'neutral' 'surprise' 'happiness' 'sadness' 'relief' 'love'
 'boredom' 'hate' 'enthusiasm' 'anger' 'empty']


Using TensorFlow backend.


[[1. 0. 0. ... 0. 0. 0.]
 [0. 1. 0. ... 0. 0. 0.]
 [0. 0. 1. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
0        1.0
1        0.0
2        0.0
3        0.0
4        0.0
        ... 
39995    0.0
39996    0.0
39997    0.0
39998    0.0
39999    0.0
Name: sentiment, Length: 40000, dtype: float32


In [7]:
print(data1.head())

                                             content  sentiment
0  [28825, 1631, 26121, 5165, 12325, 19612, 18971...        1.0
1  [13501, 16486, 22961, 15401, 9103, 9103, 19612...        0.0
2  [30054, 27939, 19612, 26121, 12325, 9103, 3005...        0.0
3  [21579, 9103, 1631, 15401, 15401, 30054, 5165,...        0.0
4  [12325, 26121, 26121, 19612, 26121, 28825, 135...        0.0


In [8]:
train_data1 , test_data1 = train_test_split(data1,test_size=0.20)
print(train_data1.shape)
print(train_data1.head())

(32000, 2)
                                                 content  sentiment
15271  [12325, 1631, 26121, 9103, 15401, 13501, 10058...        0.0
19414  [14820, 18201, 18971, 28825, 7582, 27939, 7582...        0.0
35788  [5165, 12325, 9103, 5165, 14820, 9103, 7582, 1...        0.0
11598  [9103, 28402, 9103, 21579, 30054, 18971, 18201...        1.0
11552  [12325, 9103, 30054, 18201, 18971, 22961, 9103...        0.0


In [9]:
#encoder = OneHotEncoder(handle_unknown='ignore')
#train_data1['sentiment']=(encoder.fit_transform(train_data1[['sentiment']]).toarray())
print(train_data1.head())

                                                 content  sentiment
15271  [12325, 1631, 26121, 9103, 15401, 13501, 10058...        0.0
19414  [14820, 18201, 18971, 28825, 7582, 27939, 7582...        0.0
35788  [5165, 12325, 9103, 5165, 14820, 9103, 7582, 1...        0.0
11598  [9103, 28402, 9103, 21579, 30054, 18971, 18201...        1.0
11552  [12325, 9103, 30054, 18201, 18971, 22961, 9103...        0.0


#Soumya Dip Mal

In [10]:
 print(new_datacon[0])
 print(len(new_datacon))
 print(encoded['content'])

[28825, 1631, 26121, 5165, 12325, 19612, 18971, 13501, 18201, 26121, 12325, 7582, 22961, 26121, 1631, 5165, 9103, 1631, 15401, 22961, 18971, 28825, 1631, 18201, 26121, 22961, 22961, 9103, 9103, 12325, 7582, 28825, 1631, 13501, 26121, 13501, 18201, 11290]
40000
6896


In [11]:
encoded = {k:(v+3) for k,v in encoded.items()}
encoded["<PAD>"]= 0
encoded["<START>"]= 1
encoded["<UNK>"] = 2
encoded["<UNUSED>"] = 3


In [12]:
reverse_word_index = dict([(value,key) for key,value in encoded.items()])

train_data1['content'] = keras.preprocessing.sequence.pad_sequences(train_data1['content'],value=encoded["<PAD>"],padding="post",maxlen=512)

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  This is separate from the ipykernel package so we can avoid doing imports until


In [13]:
pickle.dump(cv.vocabulary_,open("feature.pk1","wb"))

In [14]:
import keras
from sklearn.preprocessing import LabelEncoder
from keras.models import Sequential
from keras.layers import Dense,Activation,Dropout,Conv1D,Flatten
from keras.layers import Embedding

"""Prediction class label encoding
For the deep learning models we use the one-hot encoding to change the sentiment labels to numeric representations.
"""

le = LabelEncoder()
num_classes=13 
# encode train labels
y_tr = le.fit_transform(train_data1["sentiment"])
y_train = keras.utils.to_categorical(y_tr, num_classes)
# encode test labels
y_ts = le.fit_transform(test_data1["sentiment"])
y_test = keras.utils.to_categorical(y_ts, num_classes)

In [15]:
model = keras.Sequential()
model.add(keras.layers.Embedding(len(encoded),64))
model.add(keras.layers.GlobalAveragePooling1D())
model.add(keras.layers.Dense(128,activation="relu"))
model.add(keras.layers.Dense(1))

In [16]:
model.compile(optimizer="adam",loss="binary_crossentropy",metrics=["accuracy"])



Instructions for updating:
Use tf.where in 2.0, which has the same broadcast rule as np.where


In [17]:
x_val= train_data1['content'][:10000]
x_train= train_data1['content'][10000:]

y_val= train_data1['sentiment'][:10000]
y_train= train_data1['sentiment'][10000:]

#fitmodel = model.fit(x_train,y_train,epochs=40,batch_size=512,verbose=1)
print(len(x_train))
print(len(y_train))

22000
22000


In [18]:
model.fit(x_train,y_train,epochs=40,batch_size=512,validation_data=(x_val,y_val),verbose=1)


Train on 22000 samples, validate on 10000 samples
Epoch 1/40
22000/22000 [==============================] - 3s 125us/step - loss: 0.1893 - acc: 0.9554 - val_loss: 0.1933 - val_acc: 0.9537
Epoch 2/40
22000/22000 [==============================] - 2s 93us/step - loss: 0.1826 - acc: 0.9554 - val_loss: 0.1926 - val_acc: 0.9537
Epoch 3/40
22000/22000 [==============================] - 2s 92us/step - loss: 0.1821 - acc: 0.9554 - val_loss: 0.1933 - val_acc: 0.9537
Epoch 4/40
22000/22000 [==============================] - 2s 94us/step - loss: 0.1817 - acc: 0.9554 - val_loss: 0.1928 - val_acc: 0.9537
Epoch 5/40
22000/22000 [==============================] - 2s 94us/step - loss: 0.1816 - acc: 0.9554 - val_loss: 0.1945 - val_acc: 0.9537
Epoch 6/40
22000/22000 [==============================] - 2s 94us/step - loss: 0.1818 - acc: 0.9554 - val_loss: 0.1946 - val_acc: 0.9537
Epoch 7/40
22000/22000 [==============================] - 2s 95us/step - loss: 0.1814 - acc: 0.9554 - val_loss: 0.1945 - val_a

In [19]:
y_pred=model.predict(x_val)

In [20]:
model.save('final3.h5')

In [21]:
from joblib import dump
dump(model,"mlr1.save")

['mlr1.save']